const setGlobals = {
    themeClick: Array.from(document.querySelectorAll(".themeClick")),
    btnAlurithm: document.getElementById("btnAlurithm"),
    btnPersonalizado: document.getElementById("btnPersonalizado"),
    btnQRCode: document.getElementById("btnQRCode"),
    algoBannerAlurithm: document.getElementById("algoBannerAlurithm"),
    algoBannerCustom: document.getElementById("algoBannerCustom"),
    algoBannerQRCode: document.getElementById("algoBannerQRCode"),
    formContainer: document.getElementById("formContainer"),
    algoForm: document.getElementById("algoForm"),
    formLetra_a: document.getElementById("formLetra_a"),
    formLetra_e: document.getElementById("formLetra_e"),
    formLetra_i: document.getElementById("formLetra_i"),
    formLetra_o: document.getElementById("formLetra_o"),
    formLetra_u: document.getElementById("formLetra_u"),
    btnDefinirAlgo: document.getElementById("btnDefinirAlgo"),
    containerAlgoritmos: document.getElementById("containerAlgoritmos"),
    textoInput: document.getElementById("textoInput"),
    btnCriptografar: document.getElementById("btnCriptografar"),
    btnDescriptografar: document.getElementById("btnDescriptografar"),
    btnReset: document.getElementById("btnReset"),
    textoOutput: document.getElementById("textoOutput"),
    btnSalvarTexto: document.getElementById("btnSalvarTexto"),
    btnCopiar: document.getElementById("btnCopiar"),
    containerQRCode: document.getElementById("containerQRCode"),
    textoInputQR: document.getElementById("textoInputQR"),
    btnGerarQRCode: document.getElementById("btnGerarQRCode"),
    QRcanvas: document.getElementById("QRcanvas"),
    containerCards: document.getElementById("containerCards"),
    btnsCopiarTextoSalvo: document.getElementsByClassName("btnsCopiarTextoSalvo"),
    btnsExcluir: document.getElementsByClassName("btnsExcluir"),
    
    algoritmoAlurithm: {
        algo: {
            e: "enter",
            i: "imes",
            a: "ai",
            u: "ufat",
            o: "ober",
        },
        key: {
            enter: "e",
            imes: "i",
            ai: "a",
            ufat: "u",
            ober: "o",
        },
    },
};

export const globals = setGlobals;